# Generated by Django 4.2.20 on 2025-04-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('short_description', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('long_description', models.TextField(blank=True, verbose_name='Развернутое описание')),
                ('lng', models.FloatField(verbose_name='Долгота')),
                ('lan', models.FloatField(verbose_name='Широта')),
            ],
        ),
    ]
