# Generated by Django 4.2.20 on 2025-04-08 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название картинки')),
                ('type_image', models.CharField(choices=[('first_image', 'Первая картинка'), ('second_image', 'Вторая картинка')], max_length=50, verbose_name='Тип картинки')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка')),
            ],
        ),
        migrations.RenameField(
            model_name='place',
            old_name='lan',
            new_name='lat',
        ),
        migrations.AddField(
            model_name='place',
            name='first_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places_with_first_image', to='places.image', verbose_name='Первая картинка'),
        ),
        migrations.AddField(
            model_name='place',
            name='second_image',
            field=models.ManyToManyField(blank=True, related_name='places_with_second_image', to='places.image', verbose_name='Вторая картинка'),
        ),
    ]
