# Generated by Django 4.2.20 on 2025-04-09 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image_rename_lan_place_lat_place_first_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='first_image',
        ),
        migrations.RemoveField(
            model_name='place',
            name='second_image',
        ),
        migrations.AddField(
            model_name='image',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place', verbose_name='Место'),
        ),
    ]
